const fs = require('fs');
const path = require('path');

const srcDir = path.join(__dirname, 'src');
const outputFile = path.join(__dirname, 'app.js');

// Dependency order of source files
const files = [
    'state.js',
    'utils.js',
    'storage.js',
    'calculator.js',
    'charts.js',
    'chatbot.js',
    'dashboard.js',
    'app.js'
];

console.log("=== Bundling CarbonTrack AI Source Modules ===");

try {
    let bundledContent = `/* ==========================================================================\n`;
    bundledContent += `   CarbonTrack AI - Production Compiled Bundle\n`;
    bundledContent += `   DO NOT EDIT THIS FILE DIRECTLY. EDIT THE SOURCE MODULES IN /src\n`;
    bundledContent += `   ========================================================================== */\n\n`;

    files.forEach(file => {
        const filePath = path.join(srcDir, file);
        console.log(`- Bundling: ${file}`);
        if (!fs.existsSync(filePath)) {
            throw new Error(`Source file missing: ${file}`);
        }
        const content = fs.readFileSync(filePath, 'utf8');
        bundledContent += `/* ===== START OF MODULE: ${file} ===== */\n`;
        bundledContent += content.trim();
        bundledContent += `\n/* ===== END OF MODULE: ${file} ===== */\n\n`;
    });

    fs.writeFileSync(outputFile, bundledContent, 'utf8');
    console.log(`✅ Bundle successfully created: ${outputFile}`);
    console.log("Build successful");
    console.log(`Modules compiled: ${files.length}`);
} catch (error) {
    console.error(`❌ Bundling failed: ${error.message}`);
    process.exit(1);
}
